- name: Configure Docker and Deploy Insure-Me App
  hosts: all
  become: true
  tasks:
    - name: Remove conflicting containerd package (if any)
      apt:
        name: containerd
        state: absent
        purge: yes
      ignore_errors: true

    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: true

    - name: Create keyrings directory if not exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.gpg
        mode: '0644'

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Update apt cache after adding Docker repo
      apt:
        update_cache: yes

    - name: Install Docker CE
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Stop old container if exists
      shell: docker rm -f insureme || true

    - name: Pull latest Docker image
      shell: docker pull azharhashmi/insure-me:3.0

    - name: Run Docker container
      docker_container:
        name: insureme
        image: azharhashmi/insure-me:3.0
        state: started
        restart_policy: always
        ports:
          - "8084:8081"
