- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Run Docker container
      docker_container:
        name: insureme
        image: azharhashmi/insure-me:3.0
        state: started
        ports:
          - "8084:8081"
